if_snp: True
if_structure: False
if_RNA_snp_split: True
if_atac: False
if_cuttag: True


ref_genome: GRCh37d5 

yperx_threshold: 0.5


softwares:
  HIRES: /share/Data/public/biosoft/hires_utils
  HICKIT: /share/Data/public/biosoft/hickit-0.1.1_x64-linux
  HICKIT_PAIRS_TO_CON: /share/Data/public/biosoft/dip-c/scripts/hickit_pairs_to_con.sh
  HICKIT_IMPUTE_PAIRS_TO_CON: /share/Data/public/biosoft/dip-c/scripts/hickit_impute_pairs_to_con.sh
  DIP_C: /share/Data/public/biosoft/dip-c/dip-c
  HICKIT_3DG_TO_3DG_RESCALE_UNIT: /share/Data/public/biosoft/dip-c/scripts/hickit_3dg_to_3dg_rescale_unit.sh


refs:
#mouse
  GRCm38:
    bwa_mem2_index: /share/Data/public/ref_genome/mouse_ref/M23/bwamem2/genome.fa
    star_index: /share/Data/public/ref_genome/mouse_ref/M23/RNA_snp_split/CAST_B6_star_index
    annotations: /share/Data/public/ref_genome/mouse_ref/M23/raw_data/annotation.gtf
    snp: /share/Data/public/ref_genome/GRCm38/snp/Tan.CAST_B6.snp.GRCm38.withchr.txt
    par: /share/Data/public/ref_genome/GRCm38/raw_data/par.bed
    RNAsnp: /share/Data/public/ref_genome/mouse_ref/M23/RNA_snp_split/all_SNPs_CAST_EiJ_GRCm38.txt.gz

    cpg:
      20k: /share/Data/public/ref_genome/mouse_ref/M23/CpG/dipc_cpg/mm10.CpG.20000.txt
      50k: /share/Data/public/ref_genome/mouse_ref/M23/CpG/dipc_cpg/mm10.CpG.50000.txt
      200k: /share/Data/public/ref_genome/mouse_ref/M23/CpG/dipc_cpg/mm10.CpG.200000.txt
      1m: /share/Data/public/ref_genome/mouse_ref/M23/CpG/dipc_cpg/mm10.CpG.1000000.txt

#human
  GRCh37d5:
    bwa_mem2_index: /share/Data/public/ref_genome/GRCh37d5/bwa_mem2_index/genome.fa
    #star_index: /share/Data/public/ref_genome/GRCh37/star_index #如果不是GM1278就用这一行，可以获得更好的quality
    star_index: /share/Data/public/ref_genome/human_ref/GRCh37d5/RNA_snp_split/NA12878_star_index #for NA12878
    annotations: /share/Data/public/ref_genome/GRCh37/raw_data/gencode.v19.annotation.gtf
    snp: /share/Data/public/ref_genome/GRCh37/snp_file/GM12878/NA12878.withchr.txt
    par: /share/Data/public/ref_genome/GRCh37/raw_data/par.withchr.bed
    RNAsnp: /share/Data/public/ref_genome/human_ref/GRCh37d5/RNA_snp_split/NA12878.withchr.SNPsplit.txt.gz
    Index: /share/Data/public/ref_genome/human_ref/GRCh37d5/bowtie2_index/GRCh37d5
    blacklist: /share/Data/public/ref_genome/human_ref/GRCh37d5/chip/hg19-blacklist.v2.sort.bed
    filter1: chrhs37d5
    filter2: NC
    TSS_BED: /share/Data/public/ref_genome/human_ref/GRCh37d5/raw_data/tss.hg19.clean.bed
    TSS_extend: /share/Data/public/ref_genome/human_ref/GRCh37d5/raw_data/tss_extend.hg19.clean.bed
    CHROMSIZES: /share/Data/public/ref_genome/human_ref/GRCh37d5/raw_data/hg19.chr.len
    macs2_genome_size: hs
    cpg:
      20k: /share/Data/public/biosoft/hires_utils/hires_utils/reference/hg19CpG/GRCh37d5.CpG.20000.txt
      50k: /share/Data/public/biosoft/hires_utils/hires_utils/reference/hg19CpG/GRCh37d5.CpG.50000.txt
      200k: /share/Data/public/biosoft/hires_utils/hires_utils/reference/hg19CpG/GRCh37d5.CpG.200000.txt
      1m: /share/Data/public/biosoft/hires_utils/hires_utils/reference/hg19CpG/GRCh37d5.CpG.1000000.txt


split:
  ct:   XGGTTGAGGTAGTGGTATAGCTTCGTGTATAAGAGACAG;o=32
  atac: XGGTTGAGGTAGTAAGTCCTGGATGTGTATAAGAGACAG;o=32

resources:
  cutadapt_cpu_threads: 5
  bwa_cpu_threads: 8
  hires_clean_cpu_threads: 6 
  star_cpu_threads: 40
  align2pairs_cpu_threads: 6
  count_cpu_threads: 6
  generateStat_cpu_threads: 60
